- name: Install python-pycurl
  apt: pkg=python-pycurl state=latest

- name: Install Postgresql
  apt: pkg=postgresql-9.5 state=latest

- name: Install postgres contrib
  apt: pkg=postgresql-contrib state=latest

- name: Install required dependency
  apt: pkg=libpq-dev state=latest

- name: Restart PostgreSQL
  command: service postgresql restart