- name: Install python-pycurl
  apt: pkg=python-pycurl state=latest

- name: Install Postgresql
  apt: pkg=postgresql-9.5 state=latest

- name: Install postgres contrib
  apt: pkg=postgresql-contrib state=latest

- name: Install required dependency
  apt: pkg=libpq-dev state=latest

- name: Restart PostgreSQL
  command: service postgresql restart

- name: Create user
  become: yes
  become_user: 'postgres'
  command: psql -c "CREATE DATABASE deploy"

- name: Create database
  become: yes
  become_user: 'postgres'
  command: psql -c "CREATE USER deploy with PASSWORD ''"

- name: Grant privileges
  become: yes
  become_user: 'postgres'
  command: psql -c "GRANT ALL PRIVILEGES ON DATABASE deploy to deploy;"
